# Generated by Django 5.2 on 2025-05-01 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Default',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('country', models.CharField(blank=True, max_length=254, null=True)),
                ('vote', models.CharField(blank=True, max_length=254, null=True)),
                ('client', models.CharField(blank=True, max_length=254, null=True)),
                ('clientshort', models.CharField(blank=True, max_length=15, null=True)),
                ('header', models.CharField(blank=True, max_length=254, null=True)),
                ('title', models.CharField(blank=True, max_length=254, null=True)),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('index', models.CharField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=254, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('geom', models.TextField(blank=True, null=True)),
                ('zoom', models.IntegerField(blank=True, null=True)),
                ('center_lat', models.FloatField(blank=True, null=True)),
                ('center_lng', models.FloatField(blank=True, null=True)),
                ('zone_number', models.IntegerField(blank=True, null=True)),
                ('zone_letter', models.CharField(blank=True, max_length=1, null=True)),
                ('logo', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'db_table': 'default',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rainfall',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_measured', models.DateField(verbose_name='Date')),
                ('climate_scenario', models.CharField(max_length=25, verbose_name='Scneario')),
                ('year_measured', models.IntegerField(blank=True, null=True, verbose_name='Year')),
                ('month_measured', models.IntegerField(blank=True, null=True)),
                ('month_name', models.CharField(blank=True, max_length=25, null=True, verbose_name='Mon')),
                ('month_day', models.IntegerField(blank=True, null=True, verbose_name='Day')),
                ('rainfall_total', models.FloatField(blank=True, null=True, verbose_name='Total')),
                ('rainfall_max', models.FloatField(blank=True, null=True, verbose_name='Max')),
            ],
            options={
                'db_table': 'rainfall',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('code', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('area', models.FloatField(blank=True, null=True)),
                ('date_established', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=25, null=True)),
                ('data_from', models.DateField(blank=True, null=True)),
                ('data_to', models.DateField(blank=True, null=True)),
                ('operation_mode', models.CharField(blank=True, max_length=25, null=True)),
                ('station_type', models.CharField(blank=True, max_length=25, null=True)),
                ('river', models.CharField(blank=True, max_length=50, null=True)),
                ('subbasin_name', models.CharField(blank=True, max_length=254, null=True)),
                ('unit', models.CharField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=254, null=True)),
                ('basin', models.CharField(blank=True, max_length=254, null=True)),
                ('geom', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'station',
                'managed': False,
            },
        ),
    ]
