# Generated by Django 5.2 on 2025-05-09 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClimateScenario',
            fields=[
                ('climate_scenario', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('technical_code', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=1000)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'climate_scenarios',
                'managed': True,
            },
        ),
    ]
